language: php

php:
 - 5.6
 - 7.0

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
 - composer install --no-interaction $PREFER_LOWEST

script:
 - phpunit

after_script:
 - php vendor/bin/coveralls -v
